language: go
go:
  - master
script:
  - go test ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)

#install 阶段：安装依赖 travis_install_go_dependencies <go-version> [gobuild-args]
#If a Makefile is present by any of the following names, then no further actions are taken in the install step:
#
#  GNUMakefile
#  Makefile
#  BSDmakefile
#  makefile
#  In all other cases, the command go get ${gobuild_args} ./... is run.

#script 阶段：运行脚本 travis_script_go {gobuild-args}
#  make
#  Bash
#  In case there is no Makefile, it will be
#
#  go test ${gobuild_args} ./...

# 生命周期
#  before_install
#  install
#  before_script
#  script
#  aftersuccess or afterfailure
#  [OPTIONAL] before_deploy
#  [OPTIONAL] deploy
#  [OPTIONAL] after_deploy
#  after_script